spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: your-consumer-group-id

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          greetingtopic-in:
            destination: ${app.topic.greetingtopic}
            content-type: application/json
            group: your-consumer-group-id

      bindings:
        greetingtopic-in:
          destination: ${app.topic.greetingtopic}
          content-type: application/json


server:
  port: 8001
